# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MAP551 - Systèmes dynamiques
author: Marc Massot
logo: logo_MAP551.png
# Copyright year to be placed in the footer
copyright: "2023"

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 600 

# Information about where the book exists on the web
repository:
  url: https://github.com/hpc-maths/jb_map551_2022_2023  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: false
  use_repository_button: false
  home_page_in_navbar: false

launch_buttons:
  binderhub_url: https://mybinder.org

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
